version: '3'

services:
  api-server:
    build: './api-server'
    env_file:
      - '.env'
    image: missedmemo/api-server:1.0
    ports:
      - '3001:3001'

  web-server:
    build: './client'
    env_file:
      - '.env'
    depends_on:
      - 'api-server'
    image: missedmemo/web-server:1.0
    ports:
      - '3000:3000'